POST http://127.0.0.1:8000/login/
Content-Type: application/json

{
    "username": "hemanth-3",
    "password": "Hemanth@123-3"
}
###
POST http://127.0.0.1:8000/signup/
Content-Type: application/json

{
    "username": "Nikhil",
    "password": "nikhil@123",
    "email":"nikhil@gmail.com"
}
###
GET http://127.0.0.1:8000/test_token/
Content-Type: application/json
Authorization: Token 783297e542f28e18c8d15d1cfb8b0ba43fa08763
