POST http://127.0.0.1:8000/login/
Content-Type: application/json

{
    "username": "Nikhil",
    "password": "nikhil@123"
}
###
POST http://127.0.0.1:8000/signup/
Content-Type: application/json

{
    "username": "Nikhil",
    "password": "nikhil@123",
    "email":"nikhil@gmail.com"
}
###
GET http://127.0.0.1:8000/test_token/
Content-Type: application/json
Authorization: Token 032dba758174214c4b206130b5e1a1d697d3d0e1
